### ISSUE TITLE
Please fix broken build

### ISSUE THREAD

**Issue by beautifulcoder** [aspnet/Mvc#3470]
I am wondering what is the point of having a broken build up on GitHub. Correct me if I'm wrong, isn't the point of open source to invite folks to learn and contribute? I find it discouraging when code bases are hostile towards newcomers. Any person off the street should be able to pick up the code and get up to speed with a clean build. Else, I don't see much point in this being open source.

**Comment by pranavkm** [comment]
Please send a pr

**Comment by Eilon** [comment]
@beautifulcoder sorry you're seeing a broken build. Can you share more about what you're seeing? We've had some build breaks recently due to some big changes that affected multiple repos, but that should all be fixed now.

**Comment by beautifulcoder** [comment]
Yay! The build works you guys are the best. The only thing I'm seeing is a failing unit test:

    info: Exec
    info:   program: cmd
    info:   commandline: /C dnx test
    info:   workingdir: test\Microsoft.AspNet.Mvc.Core.Test
    xUnit.net DNX Runner (32-bit DNX 4.5.1)
      Discovering: Microsoft.AspNet.Mvc.Core.Test
      Discovered:  Microsoft.AspNet.Mvc.Core.Test
      Starting:    Microsoft.AspNet.Mvc.Core.Test

     Microsoft.AspNet.Mvc.ContentResultTest.ContentResult_ExecuteResultAsync_SetContentTypeAndEncoding_OnResponse(contentType: null, content: "??σµε", responseContentType: null, expectedContentType: "text/plain; charset=utf-8", expectedContentData: [206, 186, 225, 189, 185, ...]) [FAIL]
          Assert.Equal() Failure
                     (pos 0)
          Expected: text/plain; charset=utf-8
          Actual:
                     (pos 0)
          Stack Trace:
            C:\Dev\Mvc\test\Microsoft.AspNet.Mvc.Core.Test\ContentResultTest.cs(208,0): at Microsoft.AspNet.Mvc.ContentResultTest.<ContentResult_ExecuteResultAsync_SetContentTypeAndEncoding_OnResponse>d__6.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Finished:    Microsoft.AspNet.Mvc.Core.Test

**Comment by Eilon** [comment]
Ah, I think @rynowak and @Tratcher were maybe looking at this - if it's what I think it is, it's due to a recent change in another repo that we're fixing.

**Comment by Tratcher** [comment]
This was fixed on aspnetcidev this evening. However, I'm seeing a different error now:
Could not load file or assembly 'System.Private.DataContractSerialization,...

**Comment by beautifulcoder** [comment]
Awesome job guys. The build and unit tests seem to work! I'm still getting used to `dnx test` but will get a handle on it soon enough.
