### ISSUE TITLE
Misterious Messages in Views after rendering DropDwon Lists 

### ISSUE THREAD

**Issue by asoaresfil** [aspnet/Mvc#5973]
When displaying pages that use dopdown lists, at the bottom of page I get a line with messages like:

Microsoft.AspNetCore.Mvc.Rendering.SelectList (in the edit page)

```System.Collections.Generic.List`1[Microsoft.AspNetCore.Mvc.Rendering.SelectListItem]``` (in the create page)

I have 2 private methods for pupulating the lists and insert them in the ViewBags, 

```c#
//FUNCAO POPULA LOOKUP PARA CRIACAO
        private void PopulaPapeis(object PapelSelecionado = null)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Franquality", Value = "Franquality" });
            //items.Add(new SelectListItem { Text = "Consultoria", Value = "Consultoria", Selected = true });
            items.Add(new SelectListItem { Text = "Consultoria", Value = "Consultoria" });
            items.Add(new SelectListItem { Text = "RH", Value = "RH" });
            items.Add(new SelectListItem { Text = "Avaliador", Value = "Avaliador" });
            items.Add(new SelectListItem { Text = "Avaliado", Value = "Avaliado" });
            items.Add(new SelectListItem { Text = "AvaliadorAvaliado", Value = "AvaliadorAvaliado" });
            items.Add(new SelectListItem { Text = "Interessado", Value = "Interessado" });
            items.Add(new SelectListItem { Text = "Administrativo", Value = "Administrativo" });
            //var Pessoas =  _userManager.Users.ToList();

            ViewBag.Papel = items; // new SelectList(items.AsNoTracking(), "Id", "Email", PapelSelecionado);

            return;
        }

        //FUNCOES POPULA LOOKUP PARA EDICAO
        private void PopulaPapeis2(object PapelSelecionado = null) 
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Franquality", Value = "Franquality" });
            //items.Add(new SelectListItem { Text = "Consultoria", Value = "Consultoria", Selected = true });
            items.Add(new SelectListItem { Text = "Consultoria", Value = "Consultoria"});
            items.Add(new SelectListItem { Text = "RH", Value = "RH"});
            items.Add(new SelectListItem { Text = "Avaliador", Value = "Avaliador" });
            items.Add(new SelectListItem { Text = "Avaliado", Value = "Avaliado" });
            items.Add(new SelectListItem { Text = "AvaliadorAvaliado", Value = "AvaliadorAvaliado" });
            items.Add(new SelectListItem { Text = "Interessado", Value = "Interessado"});
            items.Add(new SelectListItem { Text = "Administrativo", Value = "Administrativo"});

            SelectList list = new SelectList(items, "Text", "Value",PapelSelecionado);
            ViewBag.Papel = list;

            return;
        }
```

How can I eliminate the messages at end of page? See image below. Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/3457532/23977543/88a835a2-09cd-11e7-8178-10269d8ad755.png)

**Comment by Eilon** [comment]
Hi, can you show what your CSHTML page looks like? I'm guessing there's code in the page that looks like `@ViewBag.Papel` and when you have that, Razor calls `.ToString()` on that value, which by default just shows the type's name.

**Comment by asoaresfil** [comment]
Yes, you guess it! But I could not realize what I have to change. See code above, with the @ViewBag.Papel:

`@model Feedback.Models.Textos.Ajuda

@{
    ViewData["Title"] = "Edita";
}

<h2>Edita</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Ajuda</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="id" />
        
        <div class="form-group">
            <label asp-for="Papel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="Papel" class="form-control" asp-items="ViewBag.Papel">
                    <option value="">Selecione um Papel</option>
                </select>
                
                <span asp-validation-for="Papel" class="text-danger" />
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="Pagina" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @*<input asp-for="Pagina" class="form-control" />*@
                <textarea asp-for="Pagina" id="Mensagem" class="form-control"></textarea>
                <span asp-validation-for="Pagina" class="text-danger" />
            </div>
        </div>
        
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salva" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Retorna à Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}`

**Comment by Eilon** [comment]
@asoaresfil so your issue is fixed now?

**Comment by asoaresfil** [comment]
First of all, thanks for your quick answer and feedback. Unfortunatelly, the problem still exists. Please check at http://feedback.franquality.info/ajudas (since no login is required at the moment). Click to Edit any Ajuda (Help Page) and see what appears at page bottom. 
I am not sure, but it seems that the way I've created the list is the origin of the problem, since it is no an injected list. In other similar pages where the dropdown list come from already existing models in the context, this "bottom page" message not appears. 
May be it is a conceptual mistake.  I would appreciate an orientation way to solve this.

Thank you very much n advance

**Comment by Eilon** [comment]
@asoaresfil I would recommend putting some additional text, such as `aaa` and `bbb` and `ccc` around where the bad content is being rendered in order to isolate the Razor markup that is causing this to be rendered. Or, if you could share more of your app, that would help.

**Comment by Eilon** [comment]
Closing because there is not enough information to reproduce this problem.
