### ISSUE TITLE
Argument type System.IServiceProvider [System.Private.CoreLib] is not assignable to parameter type System.IServiceProvider [System.ComponentModel]

### ISSUE THREAD

**Issue by flatproject** [aspnet/Mvc#6237]
I have an mvc core website (VS 2017, Core 1.1) with a Configure method in the Startup file like this:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
            
         if (env.IsDevelopment())
         {
              SeedData.Initialize(app.ApplicationServices);
              Configuration.Reload();
         }
}
```
And the SeedData.Initialize is like this:

`public static void Initialize(IServiceProvider serviceProvider)`

I get the following warning:
![error](https://cloud.githubusercontent.com/assets/18282373/25744044/a6d1822e-318f-11e7-91ca-8520ed798d76.png)

In order to avoid this warning I'm doing this in the configure method:
`SeedData.Initialize((IServiceProvider)app.ApplicationServices);`

Am'I doing something wrong and I get this warning? Is there a conflict in one of the packages I'm using?
How can I stop the unnecessary casting?

It's not really an issue because everything works fine, I just don't like to see the warning every time I go to the Startup code. 

I have seen in another issue #https://github.com/dotnet/corefx/issues/12678 about some Type duplications between coreclr and corefx and that you are working towards removing the duplications. Is what I see falling under this cleanup or is completely irrelevant?

**Comment by rynowak** [comment]
This is definitely strange... Are you doing anything exotic in your `csproj`? Did you manually reference `System.ComponentModel`?

**Comment by dentych** [comment]
Have the same.

I referenced a .dll from my test class library.

**Comment by pranavkm** [comment]
Almost seems like you're referencing a runtime binary (`System.Private.CoreLib`). Might help if you included your project files to see if there's an odd binary being added to your references.

**Comment by flatproject** [comment]
I don't think i do anything exotic in my .csproj and I don't remember manually referencing the `System.ComponentModel`. I always tap Alt+Enter to add the `System.ComponentModel.DataAnnotations `reference to a .cs file if adding the [Required] attribute.

Here is my .csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
  
  <ItemGroup>
    <None Update="wwwroot\**\*;Areas\**\*.cshtml">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.0.2" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="2.0.1" />
    <PackageReference Include="BuildBundlerMinifier" Version="2.4.337" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Rewrite" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\V8.Api.Services.Models\V8.Api.Services.Models.csproj" />
    <ProjectReference Include="..\V8.Api.ViewModels\V8.Api.ViewModels.csproj" />
    <ProjectReference Include="..\V8.Data\V8.Data.csproj" />
  </ItemGroup>
  
</Project>
```

Also looked through the project dependencies and the nuget cache and can't see any reference to any package `System.Private.CoreLib`.

**Comment by Eilon** [comment]
@flatproject - would you be able to share your application (e.g. in a GitHub repo) so we can take a look?

**Comment by flatproject** [comment]
Apologies for the delay. I have put the project here [https://github.com/flatproject/6237](url) stripped down to bare minimum. It compiles but not runs and the warning is still there.

![1](https://cloud.githubusercontent.com/assets/18282373/26113658/110050c8-3a53-11e7-8aae-931d4d77d2e2.png)
![2](https://cloud.githubusercontent.com/assets/18282373/26113673/1808238c-3a53-11e7-88a1-f6ac17af0555.png)

**Comment by pranavkm** [comment]
I tried your application and it seems to work fine:

![image](https://cloud.githubusercontent.com/assets/174281/26114775/15ab28cc-3a13-11e7-94f8-7bbdf33966ea.png)

Would you mind clearing your global packages directory and package cache and see if that fixes your issue? Grab nuget.exe from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe and run `nuget.exe locals -Clear All` and do a restore.

**Comment by flatproject** [comment]
@pranavkm Thanks for looking into this. I had already tried the nuget global package reset and I tried it again but still the warning shows. The application is working fine, the piece of code giving me the warning is working fine so it must be something with my setup. I will look into moving my solution to a fresh one in the next few days and hopefully it will clear up the warning.

**Comment by moattarwork** [comment]
+1

**Comment by rynowak** [comment]
Closing since this appears to be resolved

**Comment by MCGPPeters** [comment]
@flatproject  any news on this front.. having  the same issue

**Comment by flatproject** [comment]
@MCGPPeters  I moved all the code to a new solution and manually recreated all projects and the same thing happens so nothing new to report! At this point i think the issue is with the Resharper extension as most of my false positives in the past were related to Resharper. Not really sure how to test if it is Resharper or Microsoft related issue.

**Comment by fexdev** [comment]
same here but only when resharper is installed. I submitted a bug report to JetBrains.

**Comment by MPleskunina** [comment]
Hello! Please try installing the latest ReSharper 2017.2 EAP3 (https://www.jetbrains.com/resharper/eap/) and check the issue once again. Apparently, the issue is fixed in this version.

**Comment by flatproject** [comment]
@MPleskunina same issue still persists after updating today to the latest build 2017.1.3

I have cleared all nuget packages using `nuget.exe locals -Clear All` and also emptied all Resharper caches. Not sure what else i can try...

**Comment by MPleskunina** [comment]
@fexdev @flatproject The problem should be solved in the latest EAP build: https://youtrack.jetbrains.com/issue/RSRP-464676#comment=27-2290098. You can download it here: https://www.jetbrains.com/resharper/eap/.

**Comment by alexb5dh** [comment]
@MPleskunina, still having this in 2017.2 EAP 9:
``Cannot convert expression type 'System.IServiceProvider [System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]' to return type 'System.IServiceProvider [System.ComponentModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]` ``

**Comment by MPleskunina** [comment]
@alexb5dh Please feel free to comment YouTrack ticket: https://youtrack.jetbrains.com/issue/RSRP-464676.
Any information to reproduce the issue will be highly appreciated (sample solution, repro steps etc).
Thank you!
