### ISSUE TITLE
When validating IValidatableObject, ModelState has non-empty string key

### ISSUE THREAD

**Issue by dmaksim** [aspnet/Mvc#7503]
Hello,

My view model:

```c#
public class SearchViewModel : IValidatableObject
{
    // ... some properties with DataAnnotations ...

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
        yield return new ValidationResult("My object-level error");
    }
}
```

My Controller action:

```c#
// The POST comes from a standard form in cshtml
[HttpPost]
public IActionResult Search(SearchViewModel viewModel)
{
    if (!ModelState.IsValid)
        return View(viewModel);

    return Content("OK");
}
```

**Problem:**
Inside the controller action, `ModelState` has 1 error (as expected), but that error is with a key `"viewModel"` (the same as action parameter name), instead of `""` (empty string). This results in validation summary div not rendering at all in ModelOnly mode.

The problem is present when using ASP.NET Core MVC 2.1.0-preview1-final. The same code on version 2.0.6 works correctly (inserts an empty string to ModelState).

**Comment by dmaksim** [comment]
It seems that the commit https://github.com/aspnet/Mvc/commit/236ef5d1d1d12a2503c6da0900b3c40ca5470985 by @SteveSandersonMS added the logic of replacing empty string key with parameter name: https://github.com/aspnet/Mvc/blob/390ebbb258215137a1cb493d2170eda9249d4afe/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L151-L154

From what I understand, it is related to the action parameter binding feature in MVC Core 2.1, but this breaks previously working scenarios, like the one described in this issue.

Any thoughts or comments would be greatly appreciated. Thanks.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, @rynowak is the behavior introduced recently critical? Should we stick with it, or is there a way to achieve what was necessary while maintaining the old behavior?

**Comment by rynowak** [comment]
This is a breaking change, we should figure out the problem and fix it. Model State keys can definitely be empty.

**Comment by rynowak** [comment]
I believe this was addressed by @dougbu in his recent changes. See here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Validation/ValidationVisitor.cs#L151

Will attempt to repro this.

**Comment by dougbu** [comment]
@rynowak my change only maintained what @SteveSandersonMS did in 236ef5d1d1. If 236ef5d1d1 introduced a breaking change in the model state keys, we still have a breaking change from 2.0.

**Comment by dougbu** [comment]
(`Name` is analogous to what `PropertyName` was after 236ef5d1d1.)

**Comment by rynowak** [comment]
Ah gotcha, ok, well taking this one on then.

**Comment by rynowak** [comment]
It sounds like you agree with me then that if there's a problem we should fix it 😆
